---
- name: "Download logstash's apt"
  get_url:
    url: "https://artifacts.elastic.co/downloads/logstash/logstash-{{ logstash_version }}-amd64.deb"
    dest: "/tmp/logstash-{{ logstash_version }}-amd64.deb"
  register: download_logstash
  until: download_logstash is succeeded
- name: Install logstash
  become: true
  apt:
    deb: "/tmp/logstash-{{ logstash_version }}-amd64.deb"
    state: present
- name: Configure logstash
  become: true
  template:
    mode: 0644
    src: logstash.conf.j2
    dest: /etc/logstash/conf.d/logstash.conf
  notify: restart logstash
